[package]
name = "ats_usb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
bin = ["tokio/signal"]

[dependencies]
anyhow = "1.0.75"
ats_cv = { git = "https://github.com/odysseyarm/ats_cv.git" }
enumn = "0.1.13"
nalgebra = "0.32.3"
opencv-ros-camera = { version = "0.14.1" }
pin-project = "1.1.4"
serial2 = "0.2.19"
socket2 = "0.5.7"
tokio = { version = "1.32.0", features = ["macros", "rt-multi-thread", "rt", "sync", "time", "net"] }
tokio-stream = "0.1.14"
tracing = "0.1.40"
