[package]
name = "ats_cv_cbindgen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ats_cv = { path = "../ats_cv" }
cbindgen = "0.26.0"
nalgebra = "0.32.3"
