[package]
name = "vision-module-gui"
version = "0.1.0"
edition = "2021"
default-run = "vision-module-gui"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iui = { path = "../libui-rs/iui" }
serialport = "4.2.2"
specs = "0.20.0"
tokio = { version = "1.32.0", features = ["macros", "rt-multi-thread", "rt", "sync"] }
