[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[dependencies]
ats_usb = { version = "0.1.0", path = ".." }
futures = "0.3.30"
nalgebra = "0.32.5"
serialport = { version = "4.3.0", features = ["usbportinfo-interface"] }
tokio = { version = "1.38.0", features = ["signal"] }
